# # # input {
# # #   tcp {
# # #     port => 5959
# # #     codec => json_lines
# # #   }
# # # }

# # # filter {
# # #   # Rename asctime to @timestamp for Kibana compatibility
# # #   # mutate {
# # #   #   rename => { "asctime" => "@timestamp" }
# # #   # }

# # #   # # Parse the timestamp string into a real timestamp
# # #   # date {
# # #   #   match => ["@timestamp", "yyyy-MM-dd HH:mm:ss,SSS"]
# # #   #   target => "@timestamp"
# # #   # }
# # # }

# # # output {
# # #   elasticsearch {
# # #     hosts => ["http://elasticsearch:9200"]
# # #     index => "flask-app-logs-%{+YYYY.MM.dd}"
# # #   }
# # # }
# # input {
# #   udp {
# #     port => 5959
# #     codec => json
# #   }
# # }

# # output {
# #   elasticsearch {
# #     hosts => ["http://elasticsearch:9200"]
# #     index => "logstash-%{+YYYY.MM.dd}"
# #   }
# #   stdout { codec => rubydebug }
# # }
# input {
#   udp {
#     port => 5959
#     codec => json
#   }
# }

# output {
#   stdout { codec => rubydebug }
#   elasticsearch {
#     hosts => ["http://elasticsearch:9200"]
#     index => "logstash-%{+YYYY.MM.dd}"
#   }
# }

input {
  tcp {
    port => 5959
    codec => json
  }
}

output {
  stdout { codec => rubydebug }
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logstash-%{+YYYY.MM.dd}"
  }
}
