services:
  mapso:
    build: .
    ports:
      - "8001:8001"
    volumes:
      - .:/app
      - ./temp_files:/app/temp_files
    environment:
      - DEBUG=true
      - LOG_LEVEL=DEBUG
      - PYTHONPATH=/app
    command: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8001", "--reload"]